apiVersion: v1
kind: Pod
metadata:
  name: first-pod
  labels:
    app: web
    test: az1
  annotations:
    createdBy: "Marcin Kujawski , date: 19.05.2025" 
spec:
  containers:
  - name: nginx
    image: nginx:1.14.2

