apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    os: ubuntu
  name: ubuntu-pod
spec:
  containers:
  - image: ubuntu
    name: ubuntu-pod
    command: ["sh", "-c", "sleep 100d"]
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
