apiVersion: v1
kind: Pod
metadata:
  name: configmap-pod
spec:
  containers:
    - name: test-container
      image: k8s.gcr.io/busybox
      command: [ "/bin/sh", "-c", "env; while true; do sleep 3600; done"]
      env:
        - name: APP_VER
          valueFrom:
            configMapKeyRef:
              name: my-configmap
              key: VERSION
        - name: INPUT_JSON_FILE
          valueFrom:
            configMapKeyRef:
              name: my-configmap
              key: config.json
      envFrom:
        - configMapRef:
            name: from-env-file
  restartPolicy: Never
