apiVersion: v1
kind: ConfigMap
metadata:
  name: my-configmap
data:
  key1: value1
  VERSION: "1.0"
  config.json: |
    {"attr1": "value1", "attr2": "value2"}
  sshd_config: |
    PermitRootLogin=yes
    Port 2222
    adasd s
    as dsad
     adas d

