apiVersion: v1
kind: Pod
metadata:
  name: init-pod
spec:
  containers:
  - name: nginx
    image: nginx:1.19.1
  initContainers:
  - name: delay
    image: busybox
    command: ['sleep', '30']
  - name: delay2
    image: busybox
    command: ["sh", "-c", "sleep 10; echo 'Second init container done with success'"]
