apiVersion: v1
kind: Pod
metadata:
  name: liveness-pod
  labels:
    app: liveness
spec:
  containers:
  - name: busybox
    image: busybox
    command: ['sh', '-c', 'touch /tmp/healthy; sleep 30; rm -f /tmp/healthy; sleep 1d']
    livenessProbe:
      exec:
        command: ['cat', '/tmp/healthy']
      initialDelaySeconds: 5
      periodSeconds: 5
