apiVersion: v1
kind: Pod
metadata:
  name: multicontainer-pod
spec:
  containers:
  - name: web1
    image: nginx
  - name: db
    image: postgres
    env:
      - name: POSTGRES_PASSWORD
        value: "SecurePass123"
