apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: nodename-pod
  name: nodeselector-pod
spec:
  nodeSelector:
    kubernetes.io/hostname: worker02
  containers:
  - image: nginx
    name: nodename-pod
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
