apiVersion: v1
kind: Pod
metadata:
  name: readiness-pod
spec:
  containers:
  - name: my-test-app
    image: nginx:1.14.2
    readinessProbe:
      httpGet:
        path: /ready
        port: 80
      successThreshold: 3
