apiVersion: batch/v1
kind: Job
metadata:
  name: sleep-job
spec:
  # ustaw job żeby się usunał automatycznie po 45 sekundach od zakończenia Joba
  ttlSecondsAfterFinished: 45
  # uruchom się 3 razy
  completions: 3
  template:
    spec:
      containers:
      - name: sleep-job
        image: busybox
        command: ["/bin/sleep"]
        args: ["15"]
      restartPolicy: Never
