apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: nodename-pod
  name: toleration-pod
spec:
  containers:
  - image: nginx
    name: nodename-pod
  tolerations:
  - key: zone
    operator: Exists
    effect: NoSchedule
