apiVersion: v1
kind: Pod
metadata:
  name: web-init-pod
spec:
  initContainers:
  - name: check-svc
    image: 'radial/busyboxplus:curl'
    command: ["sh", "-c", "until nslookup db-svc; do echo waiting for my db-svc to start; sleep 2; done"]
  containers:
  - name: web1
    image: nginx
